export const CATEGORIES_ACTION_TYPES ={

    FETCH_CATEGORIES_START: 'FETCH_CATEORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED:'FETCH_CATEGORIES_FAILED'
}